//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupActions
    {
        public int PK_Id { get; set; }
        public int FK_Group { get; set; }
        public string ActionName { get; set; }
    
        public virtual tblGroups tblGroups { get; set; }
    }
}
